name: commit
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

defaults:
  run: # use bash for all operating systems unless overridden.
    shell: bash

jobs:
  sanity:
    name: sanity
    runs-on: ubuntu-22.04
    timeout-minutes: 90 # instead of 360 by default.

    steps:
      - name: Cancel when duplicated
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3 # shallow checkout.

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19.x'
          cache: true

      - name: Build current binary
        run: make build

      - name: Configure sysctl limits
        run: |
          sudo swapoff -a
          sudo sysctl -w vm.swappiness=1
          sudo sysctl -w fs.file-max=262144
          sudo sysctl -w vm.max_map_count=262144

      - name: Run Elasticsearch
        uses: elastic/elastic-github-actions/elasticsearch@master
        with:
          stack-version: 6.4.3
          security-enabled: false

      - name: Sanity check
        run: make sanity
