name: "release"

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+**"  # For example: v0.5.0, v0.5.1-rc2.

defaults:
  run: # use bash for all operating systems unless overridden.
    shell: bash

jobs:
  dist:
    name: dist
    runs-on: ubuntu-22.04
    timeout-minutes: 90 # instead of 360 by default.
    strategy:
      fail-fast: false # don't fail fast as sometimes failures are operating system specific.
    steps:
      - name: Cancel when duplicated
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          access_token: ${{ github.token }}

      - name: Checkout
        uses: actions/checkout@v3 # shallow checkout.

      - name: Setup Go
        uses: actions/setup-go@v3 # prepare Go. This is required for tools.
        with:
          go-version: 1.19.x
          cache: true

      - name: Set VERSION
        run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: Create release artifacts
        run: make dist

      - name: Publish release artifacts
        uses: softprops/action-gh-release@v1
        with:
          files: |
            dist/**/*.tar.gz
            dist/**/*.txt

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push images
        run: make images
